repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        require_serial: true
        types: [ python ]
        additional_dependencies: [ 'isort' ]
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3
        require_serial: true
        types: [ python ]
        additional_dependencies: [ 'black' ]
      - id: codespell
        name: codespell
        entry: codespell
        args: [ '--ignore-words-list=vas', '--skip="*.js"' ]
        language: python
        require_serial: true
        types: [ python ]
        additional_dependencies: [ 'codespell' ]
      # - id: pyright
      #   name: pyright
      #   entry: pyright --venv-path .
      #   language: node
      #   pass_filenames: false
      #   types: [ python ]
      #   additional_dependencies: [ 'pyright' ]
